[grass]
name = "grass"
id = 0
textures = { up = 1, down = 2, north = 0, south = 0, west = 0, east = 0 }

[dirt]
name = "dirt"
id = 1
textures = { up = 2, down = 2, north = 2, south = 2, west = 2, east = 2 }

[stone]
name = "stone"
id = 2
textures = { up = 3, down = 3, north = 3, south = 3, west = 3, east = 3 }

[cobblestone]
name = "cobblestone"
id = 3
textures = { up = 4, down = 4, north = 4, south = 4, west = 4, east = 4 }

